### ISSUE TITLE
Runtime error main.wlua:125:File open failed No such file or directory

### ISSUE THREAD

**Issue by yyoossk** [xFN10x/AutoPSX#1]
Runtime error main.wlua:125:File open failed No such file or directory

**Comment by xFN10x** [comment]
could be that the game id was incorrect, or that you were not connected to the internet.

did you have to manually put in the game id? and what game was it? and can you send the log file? (AutoPSX-1.0/log)

**Comment by xFN10x** [comment]
can you send the log file? it has no extenstion

**Comment by xFN10x** [comment]
closing since there is no responce
